#! /usr/bin/env python3
"""termtext

Usage:
    termtext -m <text>
    termtext --media <image>

Options:
  -h --help     Show this screen.
  --version     Show version.
  -m            send Message to your phone.
  -mms          send a picture message
"""

from docopt import docopt
import os
from twilio.rest import *

def send_remainder(text):
    auth_token  = os.environ["TWILIO_API"] 
    account_sid = os.environ["TWILIO_SID"]
    phone = Client(account_sid,auth_token)
    remainder = phone.messages.create(
        to=os.environ["YOUR_NUMBER"],         
        from_=os.environ["TWILIO_NUMBER"],
        body =text
        )


def mms(image):
    auth_token  = os.environ["TWILIO_API"] 
    account_sid = os.environ["TWILIO_SID"]
    phone = Client(account_sid,auth_token)
    remainder = phone.messages.create(
        to=os.environ["YOUR_NUMBER"],         
        from_=os.environ["TWILIO_NUMBER"],
        media_url = image,
        body="You Received a MMS via termtext",

        )


if __name__ == '__main__':

    arguments = docopt(__doc__,version='Terminal Text-1.0')
    
    if arguments['-m']:
        send_remainder(arguments['<text>'])
    elif arguments['--media']:
        mms(arguments['<image>'])
